# Generated by Django 4.2.30 on 2026-09-17 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=80)),
                ('endpoint', models.URLField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='pwp_api_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pwp_api_subscription',
            },
        ),
        migrations.CreateModel(
            name='NotificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('successful', models.BooleanField()),
                ('status_code', models.PositiveSmallIntegerField(null=True)),
                ('error', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='notification_results', to='pwp_api.subscription')),
            ],
            options={
                'db_table': 'pwp_api_notification_result',
            },
        ),
    ]
